const header = document.getElementById('header');
const headerLogo = document.getElementById('headerLogo');
const nav = document.getElementById('nav');
const hero = document.getElementById('hero');
const heroTitle = document.getElementById('heroTitle');
const heroSubtitle = document.getElementById('heroSubtitle');
const downloadBtns = document.getElementById('downloadBtns');
const download = document.getElementById('download');
const downloadText = document.getElementById('downloadText');
const mobWarning = document.getElementById('mobWarning');
export { header, headerLogo, nav, hero, heroTitle, heroSubtitle, downloadBtns, download, downloadText, mobWarning };
